[package]
name = "solver-wasm"
version = "0.0.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
sha2 = "0.10"
wee_alloc = { version = "0.4", default-features = false }

[profile.release]
lto = true
